Question-1

In [ ]:
#name: Naomi Thing
#student ID: 2332244

import numpy as np

def get_matrix():
  """This function prompts the user to input 9 numbers and returns a 3x3 matrix containing these values."""
  matrix = []
  for i in range(3):
    row = []
    for j in range(3):
      while True:
        try:
          value = float(input(f"enter value for ({i+1},{j+1}): "))
          row.append(value)
          break
        except ValueError:
          print("Invalid input. Please enter a number.")
    matrix.append(row)
  return np.array(matrix)

def print_matrix(matrix):
  """This function takes a matrix and prints it to the console."""
  for row in matrix:
    for value in row:
      print(value, end=' ')
    print()
  print()

def main():
  A = get_matrix()

  #print the matrix A
  print("Matrix A: ")
  print_matrix(A)

  #print the determinant of A
  deter = np.linalg.det(A)
  print(f"Determinant of A: {deter}\n")

  #print the inverse of A(if it exists)
  if deter==0:
    print("Inverse of A does not exist.")
  else:
    A_inv = np.linalg.inv(A)
    print("Inverse of A: ")
    print_matrix(A_inv)

  #print the result of A*A and A*A*A
  print("A*A: ")
  print_matrix(A.dot(A))
  print("A*A*A: ")
  print_matrix(A.dot(A).dot(A))

  #print the number of values in A that are >=10
  count = 0
  for row in A:
    for value in row:
      if value >=10:
        count +=1
  print(f"Number of values in A that are >= 10: {count}")

if __name__ == '__main__':
  main()

enter value for (1,1): 2
enter value for (1,2): 3
enter value for (1,3): 4
enter value for (2,1): 1
enter value for (2,2): 55
enter value for (2,3): 6
enter value for (3,1): 4
enter value for (3,2): 7
enter value for (3,3): 3
Matrix A: 
2.0 3.0 4.0 
1.0 55.0 6.0 
4.0 7.0 3.0 

Determinant of A: -543.0000000000003

Inverse of A: 
-0.22651933701657462 -0.034990791896869246 0.37200736648250465 
-0.038674033149171276 0.01841620626151013 0.014732965009208107 
0.3922651933701658 0.0036832412523020264 -0.19705340699815843 

A*A: 
23.0 199.0 38.0 
81.0 3070.0 352.0 
27.0 418.0 67.0 

A*A*A: 
397.0 11280.0 1400.0 
4640.0 171557.0 19800.0 
740.0 23540.0 2817.0 

Number of values in A that are >= 10: 1


Question-2

In [7]:
#name: Naomi Thing
#student ID: 2332244

import numpy as np

def input_matrix(dim):
  """Takes input from user to create a square matrix of given dimension.
  Returns the matrix as a numpy array."""
  while True:
    try: #initialize a 2D array of zeros to store the matrix
      matrix=np.zeros((dim, dim))
      for i in range(dim): #iterate over each row and column to get input from user
        for j in range(dim):
          #promt useer to enter value at current position
          matrix[i][j] = int(input(f"enter element at row {i+1} and column {j+1}: "))
      return matrix #return the matrix as a numpy array
    except:
      #if input is invalid, display error message and prompt again
      print("Invalid input. please try again")
      continue

def diagonal_sum(matrix):
  """Calculates the sum of diagonal elements of a square matrix.
  Returns the sum."""
  #extract diagonal elements of matrix as a 1D array using np.diag()
  diagonal = np.diag(matrix)
  #calculate sum of diagonal elements using np.sum()
  return np.sum(diagonal)

def main():
  while True:
    try:
      dim = int(input("enter the dimension of the square matrix: "))
      if dim > 0:
        matrix = input_matrix(dim)#call input_matrix() function to get matrix from user
        print("your matrix: ") #display the matrix of user
        print(matrix)
        #call diagonal_sum() function to claculate diagonal sum 
        diagonal = diagonal_sum(matrix)
        #display diagonal sum to the user
        print(f"the sum of diagonal elements of the matrix is: {diagonal}")
        break
      else:
        #if dimension is invalid, display error message and prompt again
        print("dimension should be greater than 0")
        continue
    except:
      #if input is invalid, display error message and prompt again
      print("Invalid input, please try again.")
      continue
    
  while True:
    try:
      #prompt user to decide whether to run the program again or not
      conn = input("\nDo you want to run the program again? (Y/N): ")
      if conn.lower()=="y":
        #if user wants to run again, call main() function again
        main()
      elif conn.lower()=="n":
        #if user does not want to run again, display exit message
        print("thank you for using the program. Goodbye!")
        break
      else:
        #if input is invalid, display error message and prompt again
        print("Invalid input, please enter Y or N.")
        continue
      break
    except:
      print("Invalid input, please try again!")
      continue
#call main() function to start the program
main()

enter the dimension of the square matrix: 0
dimension should be greater than 0
enter the dimension of the square matrix: 3
enter element at row 1 and column 1: 1
enter element at row 1 and column 2: 2
enter element at row 1 and column 3: 3
enter element at row 2 and column 1: 4
enter element at row 2 and column 2: 5
enter element at row 2 and column 3: 6
enter element at row 3 and column 1: 7
enter element at row 3 and column 2: 8
enter element at row 3 and column 3: 9
your matrix: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
the sum of diagonal elements of the matrix is: 15.0

Do you want to run the program again? (Y/N): N
thank you for using the program. Goodbye!


Question-3

In [8]:
#name: Naomi Thing
#stduent ID: 2332244

def ackermann(m,n):
  #base case 1: A(0,n)=n+1
  if m==0:
    return n+1,1
    #base case 2: A(m,0)=A(m-1,1)
  elif m>0 and n==0:
    #recursively evaluate A(m-1,1)
    count=1
    result, count_sub = ackermann(m-1,1)
    count += count_sub #increment the recursive call count by the count for the sub-call
    return result, count
  else: #recursive case: A(m,n)=A(m-1,A(m,n-1))
    count=1
    #recursively evaluate A(m,n-1)
    result_inner, count_inner=ackermann(m,n-1)
    #increment the recursive call count by the count for the inner call
    count += count_inner
    #recursively evaluate A(m-1,A(m,n-1))
    result, count_sub=ackermann(m-1,result_inner)
    #increment the recursvie call count by the count for the sub-call
    count += count_sub
    return result, count

m=2
n=3
result, count=ackermann(m,n) #call the function and get the result and the total number of recursive calls
#print the result and the total number of recursive calls
print(f"Result: ackermann({m},{n}) is {result}")
print(f"The number of times the function ackermann({m},{n}) has been called is: {count}")


Result: ackermann(2,3) ==> 9
The number of times the function ackermann(2,3) has been called is: 44
